language: java
sudo: false
install: true

dist: trusty

jdk:
- oraclejdk8

os:
- linux

branches:
  only:
  - develop

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

addons:
  sonarcloud:
    organization: $SONARCLOUD_ORGANIZATION
    token:
      secure: $SONARCLOUD_TOKEN

#ERROR: You're only authorized to execute a local (preview) SonarQube analysis without pushing the results to the SonarQube server. Please contact your SonarQube administrator.
#this error when script write - "- sonar-scanner" with out parameters
script:
- ./gradlew assemble
- ./gradlew check --rerun-tasks
- sonar-scanner -Dsonar.projectKey=sourceparse-gradle -Dsonar.organization=rmunirov-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=09bbea5321523c31b8d9800ee04f1205a4893466
- rm -rf .scannerwork